"""Add user table

Revision ID: 042fb006760d
Revises: 
Create Date: 2026-01-12 14:47:05.207804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '042fb006760d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('supplier_email', sa.String(length=255), nullable=True),
    sa.Column('invoice_number', sa.String(length=255), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('invoice_type', sa.String(length=50), nullable=True),
    sa.Column('job_reference', sa.String(length=255), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('pdf_filename', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('email_subject', sa.String(length=500), nullable=True),
    sa.Column('email_date', sa.DateTime(), nullable=True),
    sa.Column('gmail_message_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gmail_message_id')
    )
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_job_reference'), ['job_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_supplier_name'), ['supplier_name'], unique=False)

    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qb_id', sa.String(length=255), nullable=False),
    sa.Column('qb_sync_token', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('purchase_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_qb_id'), ['qb_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_product_sku'), ['sku'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_sku'))
        batch_op.drop_index(batch_op.f('ix_product_qb_id'))

    op.drop_table('product')
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_supplier_name'))
        batch_op.drop_index(batch_op.f('ix_invoice_status'))
        batch_op.drop_index(batch_op.f('ix_invoice_job_reference'))
        batch_op.drop_index(batch_op.f('ix_invoice_created_at'))

    op.drop_table('invoice')
    # ### end Alembic commands ###
