"""Add invoice storage with line items

Revision ID: 0d5d342b6798
Revises: 042fb006760d
Create Date: 2026-01-12 15:06:06.934793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d5d342b6798'
down_revision = '042fb006760d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('original_unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cost_per_item', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('markup_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('profit_per_item', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.create_index('idx_item_part_number', ['part_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_item_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_item_part_number'), ['part_number'], unique=False)

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_consolidated', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('order_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_orders', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('total_selling', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('total_profit', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('average_markup', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('items_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('parser_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('confidence', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('needs_review', sa.Boolean(), nullable=True))
        batch_op.create_index('idx_invoice_job_ref', ['job_reference'], unique=False)
        batch_op.create_index('idx_invoice_supplier_date', ['supplier_name', sa.text('created_at DESC')], unique=False)
        batch_op.create_index('idx_invoice_user_created', ['user_id', sa.text('created_at DESC')], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_invoice_number'), ['invoice_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('gmail_message_id')
        batch_op.drop_column('email_subject')
        batch_op.drop_column('invoice_type')
        batch_op.drop_column('email_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('invoice_type', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('email_subject', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('gmail_message_id', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_invoice_user_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_invoice_number'))
        batch_op.drop_index('idx_invoice_user_created')
        batch_op.drop_index('idx_invoice_supplier_date')
        batch_op.drop_index('idx_invoice_job_ref')
        batch_op.drop_column('needs_review')
        batch_op.drop_column('confidence')
        batch_op.drop_column('parser_method')
        batch_op.drop_column('items_count')
        batch_op.drop_column('average_markup')
        batch_op.drop_column('total_profit')
        batch_op.drop_column('total_selling')
        batch_op.drop_column('total_cost')
        batch_op.drop_column('total_orders')
        batch_op.drop_column('order_number')
        batch_op.drop_column('is_consolidated')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_item_part_number'))
        batch_op.drop_index(batch_op.f('ix_invoice_item_invoice_id'))
        batch_op.drop_index('idx_item_part_number')

    op.drop_table('invoice_item')
    # ### end Alembic commands ###
