"""Add Xero sync fields

Revision ID: 4e9fe730a2c5
Revises: df8bf3698c91
Create Date: 2026-01-20 13:54:34.535137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e9fe730a2c5'
down_revision = 'df8bf3698c91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xero_invoice_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('xero_synced_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('xero_quote_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('xero_quote_synced_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.alter_column('part_number',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('cost_per_item',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=False)
        batch_op.alter_column('selling_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=True)
        batch_op.alter_column('profit_per_item',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('discount_percent')
        batch_op.drop_column('original_unit_price')
        batch_op.drop_column('markup_percent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('markup_percent', sa.NUMERIC(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('original_unit_price', sa.NUMERIC(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('discount_percent', sa.NUMERIC(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.alter_column('profit_per_item',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('selling_price',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('cost_per_item',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('part_number',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('xero_quote_synced_at')
        batch_op.drop_column('xero_quote_id')
        batch_op.drop_column('xero_synced_at')
        batch_op.drop_column('xero_invoice_id')

    # ### end Alembic commands ###
