"""Add Paddle fields to User model

Revision ID: abb8d1f96b59
Revises: 4e9fe730a2c5
Create Date: 2026-01-21 08:47:54.048585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abb8d1f96b59'
down_revision = '4e9fe730a2c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_unit_price', sa.Numeric(precision=10, scale=4), nullable=True))
        batch_op.add_column(sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('markup_percent', sa.Numeric(precision=5, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.drop_column('markup_percent')
        batch_op.drop_column('discount_percent')
        batch_op.drop_column('original_unit_price')

    # ### end Alembic commands ###
