"""Add part number corrections table

Revision ID: c589dcee8aed
Revises: abb8d1f96b59
Create Date: 2026-01-23 07:55:26.725191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c589dcee8aed'
down_revision = 'abb8d1f96b59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('part_number_correction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('original_ocr', sa.String(length=100), nullable=False),
    sa.Column('corrected_part', sa.String(length=100), nullable=False),
    sa.Column('times_applied', sa.Integer(), nullable=True),
    sa.Column('times_confirmed', sa.Integer(), nullable=True),
    sa.Column('source_invoice_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_applied_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['source_invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('part_number_correction', schema=None) as batch_op:
        batch_op.create_index('idx_correction_active', ['is_active'], unique=False)
        batch_op.create_index('idx_correction_supplier', ['supplier_name'], unique=False)
        batch_op.create_index('idx_correction_user_ocr', ['user_id', 'original_ocr'], unique=False)
        batch_op.create_index(batch_op.f('ix_part_number_correction_corrected_part'), ['corrected_part'], unique=False)
        batch_op.create_index(batch_op.f('ix_part_number_correction_original_ocr'), ['original_ocr'], unique=False)
        batch_op.create_index(batch_op.f('ix_part_number_correction_supplier_name'), ['supplier_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_part_number_correction_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paddle_customer_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('paddle_subscription_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('paddle_subscription_id')
        batch_op.drop_column('paddle_customer_id')

    with op.batch_alter_table('part_number_correction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_part_number_correction_user_id'))
        batch_op.drop_index(batch_op.f('ix_part_number_correction_supplier_name'))
        batch_op.drop_index(batch_op.f('ix_part_number_correction_original_ocr'))
        batch_op.drop_index(batch_op.f('ix_part_number_correction_corrected_part'))
        batch_op.drop_index('idx_correction_user_ocr')
        batch_op.drop_index('idx_correction_supplier')
        batch_op.drop_index('idx_correction_active')

    op.drop_table('part_number_correction')
    # ### end Alembic commands ###
