"""Add Xero connection table

Revision ID: df8bf3698c91
Revises: c06687f172c4
Create Date: 2026-01-19 16:30:01.184591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df8bf3698c91'
down_revision = 'c06687f172c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token'), ['token'], unique=True)

    op.create_table('quickbooks_connection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('realm_id', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('default_income_account_id', sa.String(length=50), nullable=True),
    sa.Column('default_income_account_name', sa.String(length=255), nullable=True),
    sa.Column('default_expense_account_id', sa.String(length=50), nullable=True),
    sa.Column('default_expense_account_name', sa.String(length=255), nullable=True),
    sa.Column('auto_sync', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('supplier_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_name', sa.String(length=100), nullable=False),
    sa.Column('account_number', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('invoice_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_name', 'account_number', name='uq_supplier_account')
    )
    with op.batch_alter_table('supplier_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_account_account_number'), ['account_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_account_supplier_name'), ['supplier_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_account_user_id'), ['user_id'], unique=False)

    op.create_table('xero_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_name', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('connected_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('default_expense_account_code', sa.String(length=50), nullable=True),
    sa.Column('default_expense_account_name', sa.String(length=255), nullable=True),
    sa.Column('default_sales_account_code', sa.String(length=50), nullable=True),
    sa.Column('default_sales_account_name', sa.String(length=255), nullable=True),
    sa.Column('auto_sync', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('qb_estimate_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('qb_estimate_synced_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('matched_customer_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('matched_customer_name', sa.String(length=255), nullable=True))
        batch_op.create_index('idx_invoice_doc_type', ['document_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_document_type'), ['document_type'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_plan', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('subscription_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('trial_ends_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('subscription_ends_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('subscription_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('bonus_invoices', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('setup_completed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('tour_completed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('company_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('default_markup', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('trial_reminder_sent', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('trial_reminder_sent')
        batch_op.drop_column('default_markup')
        batch_op.drop_column('company_name')
        batch_op.drop_column('tour_completed')
        batch_op.drop_column('setup_completed')
        batch_op.drop_column('bonus_invoices')
        batch_op.drop_column('subscription_started_at')
        batch_op.drop_column('subscription_ends_at')
        batch_op.drop_column('trial_ends_at')
        batch_op.drop_column('stripe_subscription_id')
        batch_op.drop_column('stripe_customer_id')
        batch_op.drop_column('subscription_status')
        batch_op.drop_column('subscription_plan')

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_document_type'))
        batch_op.drop_index('idx_invoice_doc_type')
        batch_op.drop_column('matched_customer_name')
        batch_op.drop_column('matched_customer_id')
        batch_op.drop_column('qb_estimate_synced_at')
        batch_op.drop_column('qb_estimate_id')
        batch_op.drop_column('document_type')

    op.drop_table('xero_connections')
    with op.batch_alter_table('supplier_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_account_user_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_account_supplier_name'))
        batch_op.drop_index(batch_op.f('ix_supplier_account_account_number'))

    op.drop_table('supplier_account')
    op.drop_table('quickbooks_connection')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token'))

    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
